name: Create diagram
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 13 * * 1"
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
          file_colors: '{"py": "#FF0000,"svg": "#FF7F00","txt":"#FFFF00","wav": "#00FF00","kra": "#0000FF","md": "#4B0082","LICENSE": "#9400D3"}'
          output_file: Other/diagram.svg
