name: Create diagram
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 13 * * 1"
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
          # file_colors: '{"py": "red","svg": "orange","txt":"yellow","wav": "green","kra": "cyan","md": "blue","gitignore": "purple,"LICENSE": "pink}'
          excluded_globs: '**/*.{,LICENSE}'
          output_file: Other/diagram.svg
