name: Create diagram
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 13 * * 1"
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          excluded_paths: ".github"
