name: Checkout submodules
on: [push]
jobs:
  Auto-Submodule-Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
