name: Checkout submodules
on: [push]
jobs:
  Auto-Submodule-Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout submodules
  # You may pin to the exact commit or the version.
  # uses: textbook/git-checkout-submodule-action@0cb23c7e6a67085e1dc5e884920bd620f7b9c469
      uses: textbook/git-checkout-submodule-action@2.1.1
      with:
    # Set the --remote flag
        remote: true # optional
