name: update all submodules
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  buils:
    runs-on: ubuntu-latest
    name: Update Submodules and push
    steps:
    - name: Checkout local repository
      uses: actions/checkout@v3
    - name: Submodule update
      run: |
        git submodule init
        git submodule update --remote --merge
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "update submodule" -a
    - name: Push to protected branch
      uses: CasperWA/push-protected@v2
      with:
        token: ${{ secrets.PUSH_TO_PROTECTED_BRANCH }}
        branch: main
        unprotect_reviews: true
